spring:
  cloud:
    azure:
      eventhubs:
        namespace: 'ent-audit-namespace'
        processor:
          checkpoint-store:
            container-name: 'content'
            account-name:  'sefenterprisestorage'
    function:
      definition: supply
    stream:
      bindings:
        consume-in-0:
          destination: 'audit-eh'
          group: '$Default'
        supply-out-0:
          destination: 'audit-eh' # same as the above destination
      eventhubs:
        bindings:
          consume-in-0:
            consumer:
              checkpoint:
                mode: MANUAL
      default:
        producer:
          errorChannelEnabled: true
      poller:
        initial-delay: 0
        fixed-delay: 2000
